name: 'Setup Rust'

description: 'Setup rust'

inputs:
  # See https://rust-lang.github.io/rustup/concepts/components.html
  components:
    required: false
    type: string
    description: space separated Rust components, e.g. `clippy rustfmt rust-docs`

  tools:
    required: false
    type: string
    description: comma separated Cargo tools

  restore-cache:
    default: true
    required: false
    type: boolean
    description: whether to restore cache

  save-cache:
    default: false
    required: false
    type: boolean
    description: whether to save cache, e.g. `github.ref_name == 'main'`

  cache-key:
    default: 'main'
    required: false
    type: string
    description: cache key prefix

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    - name: Setup Rust cache
      if: inputs.restore-cache == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: ${{ inputs.cache-key }}
        save-if: ${{ inputs.save-cache }}

    - name: Install cargo tools
      if: inputs.tools != ''
      shell: bash
      run: |
        IFS=',' read -ra TOOLS <<< "${{ inputs.tools }}"
        for tool in "${TOOLS[@]}"; do
          tool=$(echo "$tool" | xargs)  # trim whitespace
          echo "Installing $tool..."
          cargo install "$tool" --locked || echo "⚠️  Failed to install $tool"
        done
