//! Changelog configuration types

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Changelog configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChangelogConfig {
    /// Changelog template
    pub template: ChangelogTemplate,

    /// How to group commits
    pub grouping: CommitGrouping,

    /// Output format
    pub output_format: ChangelogFormat,

    /// Whether to include breaking changes section
    pub include_breaking_changes: bool,

    /// Conventional commit type mappings
    pub conventional_commit_types: HashMap<String, String>,
}

impl Default for ChangelogConfig {
    fn default() -> Self {
        let mut types = HashMap::new();
        types.insert("feat".to_string(), "Features".to_string());
        types.insert("fix".to_string(), "Bug Fixes".to_string());
        types.insert("docs".to_string(), "Documentation".to_string());
        types.insert("style".to_string(), "Styles".to_string());
        types.insert("refactor".to_string(), "Code Refactoring".to_string());
        types.insert("perf".to_string(), "Performance Improvements".to_string());
        types.insert("test".to_string(), "Tests".to_string());
        types.insert("build".to_string(), "Build System".to_string());
        types.insert("ci".to_string(), "Continuous Integration".to_string());
        types.insert("chore".to_string(), "Chores".to_string());
        types.insert("revert".to_string(), "Reverts".to_string());

        Self {
            template: ChangelogTemplate::default(),
            grouping: CommitGrouping::Type,
            output_format: ChangelogFormat::Markdown,
            include_breaking_changes: true,
            conventional_commit_types: types,
        }
    }
}

/// Changelog template configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChangelogTemplate {
    /// Header template
    pub header_template: String,

    /// Section template
    pub section_template: String,

    /// Commit template
    pub commit_template: String,

    /// Footer template
    pub footer_template: String,
}

impl Default for ChangelogTemplate {
    fn default() -> Self {
        Self {
            header_template: "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n".to_string(),
            section_template: "## [{version}] - {date}\n\n".to_string(),
            commit_template: "- {description} ([{hash}]({url}))\n".to_string(),
            footer_template: "\n---\n\nGenerated by [Sublime Monorepo Tools](https://github.com/websublime/workspace-node-tools)\n".to_string(),
        }
    }
}

/// How to group commits in changelog
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommitGrouping {
    /// Group by commit type
    Type,
    /// Group by scope
    Scope,
    /// No grouping
    None,
}

/// Changelog output format
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ChangelogFormat {
    /// Markdown format
    Markdown,
    /// Plain text format
    Text,
    /// JSON format
    Json,
}