use std::fs::File;
use std::io::Write;
use std::path::Path;

use crate::fixtures::write_file;

/// Add yarn package manager files
pub fn add_yarn_manager(repo_path: &Path) -> std::io::Result<()> {
    let yarn_lock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n";
    write_file(&repo_path.join("yarn.lock"), yarn_lock)
}

/// Add pnpm package manager files
pub fn add_pnpm_manager(repo_path: &Path) -> std::io::Result<()> {
    let pnpm_lock = "lockfileVersion: '9.0'\n";
    let pnpm_workspace = "packages\n - packages/*\n";

    write_file(&repo_path.join("pnpm-lock.yaml"), pnpm_lock)?;
    write_file(&repo_path.join("pnpm-workspace.yaml"), pnpm_workspace)
}

/// Add bun package manager files
pub fn add_bun_manager(repo_path: &Path) -> std::io::Result<()> {
    // For bun, we'll create an empty lock file since the content would be binary
    let bun_lock = Path::new(&repo_path).join("bun.lockb");
    let mut file = File::create(bun_lock)?;
    file.write_all(&[0u8; 10])?; // Just write some dummy binary content
    Ok(())
}

/// Add npm package manager files
pub fn add_npm_manager(repo_path: &Path) -> std::io::Result<()> {
    let package_lock = "{\n  \"name\": \"root\",\n  \"lockfileVersion\": 3\n}\n";
    write_file(&repo_path.join("package-lock.json"), package_lock)
}
