/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * MonorepoProject class.
 * Represents a monorepo project. If `root` is not provided, it defaults to the current working directory.
 * If the `project.json` file is not found, it will be created. If the monorepo cannot be detected, an error will be thrown.
 *
 * @class MonorepoProject - The MonorepoProject class.
 * @param {string|undefined} root - The root of the monorepo.
 * @throws {Error} If the monorepo cannot be detected.
 *
 * @example
 *
 * ```typescript
 * const monorepoProject = new MonorepoProject(".");
 * ```
 */
export declare class MonorepoProject {
  constructor(root?: string)
  /**
   * Get project(monorepo) root information.
   *
   * @returns {MonorepoProjectDescription} - The project description.
   * @throws {Error} If the project cannot be detected.
   */
  getProjectDescription(): MonorepoProjectDescription
  /**
   * Validate the project and return the validation status.
   *
   * @returns {Object} - The validation status.
   * @throws {Error} If the project cannot be validated.
   */
validate(): {status: string; messages: string[]}
/**
 * Get the workspace descriptor. Packages information.
 *
 * @returns {Array<{absolute_path: string; location: string; name: string; version: string; workspace_dependencies: string[]; workspace_dev_dependencies: string[];}>}
 * @throws {Error} If the project cannot be detected.
 * @throws {Error} If the project cannot be validated.
 * @throws {Error} If the project cannot be loaded.
 */
getWorkspaceDescriptor(): Array<{absolute_path: string; location: string; name: string; version: string; workspace_dependencies: string[]; workspace_dev_dependencies: string[];}>
/**
 * Get the package descriptor. Package information.
 *
 * @param {string} package - The package name.
 * @returns {Object} - The package descriptor.
 * @throws {Error} If the project cannot be detected.
 * @throws {Error} If the package cannot be found.
 */
getPackageDescriptor(package: string): {absolute_path: string; location: string; name: string; version: string; workspace_dependencies: string[]; workspace_dev_dependencies: string[];}
/**
 * Get the workspace dependency graph. Packages dependency information.
 *
 * @returns {Object} - The workspace dependency graph.
 * @throws {Error} If the project cannot be detected.
 */
getWorkspaceDependencyGraph(): Record<string, string[]>
}

export declare function getVersion(): string

export interface MonorepoProjectDescription {
  root: string
  packageJson: any
  packageManager: string
}
