// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { createRequire } = require('node:module')
require = createRequire(__filename)

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  const report = typeof process.report.getReport === 'function' ? process.report.getReport() : null
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./workspace-tools.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm') {
      try {
        return require('./workspace-tools.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-android-arm-eabi')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./workspace-tools.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-win32-x64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'ia32') {
      try {
        return require('./workspace-tools.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-win32-ia32-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('./workspace-tools.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-win32-arm64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
        return require('./workspace-tools.darwin-universal.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-darwin-universal')
      } catch (e) {
        loadErrors.push(e)
      }

    if (process.arch === 'x64') {
      try {
        return require('./workspace-tools.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-darwin-x64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('./workspace-tools.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-darwin-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./workspace-tools.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-freebsd-x64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('./workspace-tools.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-freebsd-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
        return require('./workspace-tools.linux-x64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-x64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./workspace-tools.linux-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-x64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
        return require('./workspace-tools.linux-arm64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-arm64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./workspace-tools.linux-arm64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-arm64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
        return require('./workspace-tools.linux-arm-musleabihf.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-arm-musleabihf')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./workspace-tools.linux-arm-gnueabihf.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-arm-gnueabihf')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
        return require('./workspace-tools.linux-riscv64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-riscv64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./workspace-tools.linux-riscv64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-riscv64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./workspace-tools.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-ppc64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 's390x') {
      try {
        return require('./workspace-tools.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@websublime/workspace-tools-linux-s390x-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('./workspace-tools.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('@websublime/workspace-tools-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    // TODO Link to documentation with potential fixes
    //  - The package owner could build/publish bindings for this arch
    //  - The user may need to bundle the correct files
    //  - The user may need to re-install node_modules to get new packages
    throw new Error('Failed to load native binding', { cause: loadErrors })
  }
  throw new Error(`Failed to load native binding`)
}

module.exports.Dependency = nativeBinding.Dependency
module.exports.Package = nativeBinding.Package
module.exports.addChange = nativeBinding.addChange
module.exports.bumpMajor = nativeBinding.bumpMajor
module.exports.bumpMinor = nativeBinding.bumpMinor
module.exports.bumpPatch = nativeBinding.bumpPatch
module.exports.bumpSnapshot = nativeBinding.bumpSnapshot
module.exports.changeExists = nativeBinding.changeExists
module.exports.detectPackageManager = nativeBinding.detectPackageManager
module.exports.executeCmd = nativeBinding.executeCmd
module.exports.getChanges = nativeBinding.getChanges
module.exports.getChangesByBranch = nativeBinding.getChangesByBranch
module.exports.getChangesByPackage = nativeBinding.getChangesByPackage
module.exports.getChangesMetaByPackage = nativeBinding.getChangesMetaByPackage
module.exports.getConfig = nativeBinding.getConfig
module.exports.getPackageScopeNameVersion = nativeBinding.getPackageScopeNameVersion
module.exports.getProjectRootPath = nativeBinding.getProjectRootPath
module.exports.initChanges = nativeBinding.initChanges
module.exports.isVcsRepository = nativeBinding.isVcsRepository
module.exports.removeChange = nativeBinding.removeChange
module.exports.repoAdd = nativeBinding.repoAdd
module.exports.repoAddAll = nativeBinding.repoAddAll
module.exports.repoCheckout = nativeBinding.repoCheckout
module.exports.repoCommit = nativeBinding.repoCommit
module.exports.repoConfig = nativeBinding.repoConfig
module.exports.repoCreateBranch = nativeBinding.repoCreateBranch
module.exports.repoCreateTag = nativeBinding.repoCreateTag
module.exports.repoFetchAll = nativeBinding.repoFetchAll
module.exports.repoGetAllFilesChangedSinceBranch = nativeBinding.repoGetAllFilesChangedSinceBranch
module.exports.repoGetAllFilesChangedSinceSha = nativeBinding.repoGetAllFilesChangedSinceSha
module.exports.repoGetBranchFromCommit = nativeBinding.repoGetBranchFromCommit
module.exports.repoGetCommitsSince = nativeBinding.repoGetCommitsSince
module.exports.repoGetCurrentBranch = nativeBinding.repoGetCurrentBranch
module.exports.repoGetCurrentSha = nativeBinding.repoGetCurrentSha
module.exports.repoGetDivergedCommit = nativeBinding.repoGetDivergedCommit
module.exports.repoGetFirstSha = nativeBinding.repoGetFirstSha
module.exports.repoGetPreviousSha = nativeBinding.repoGetPreviousSha
module.exports.repoGetTags = nativeBinding.repoGetTags
module.exports.repoInit = nativeBinding.repoInit
module.exports.repoIsVcs = nativeBinding.repoIsVcs
module.exports.repoMerge = nativeBinding.repoMerge
module.exports.repoPush = nativeBinding.repoPush
