/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Returns the version of the crate.
 *
 * This function is exposed to Node.js and returns the current version
 * of the `sublime_node_tools` crate.
 *
 * # Returns
 *
 * A string containing the semantic version of the crate.
 *
 * # Examples
 *
 * ```typescript
 * import { getVersion } from '@websublime/workspace-tools';
 *
 * console.log(`Using workspace-tools version: ${getVersion()}`);
 * ```
 */
export declare function getVersion(): string
