/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Git branch information.
 *
 * Contains the name of the current Git branch, if available.
 * This information is useful for determining the context of
 * pending changesets and version bumps.
 *
 * # Fields
 *
 * - `name`: The branch name
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface BranchInfo {
 *   Branch name
 *   name: string;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * const branch: BranchInfo = { name: 'main' };
 * const feature: BranchInfo = { name: 'feature/add-new-api' };
 * ```
 */
export interface BranchInfo {
  /**
   * Git branch name.
   *
   * This is the name of the currently checked-out branch.
   * It does not include the `refs/heads/` prefix.
   */
  name: string
}

/**
 * Changeset information.
 *
 * Represents a pending changeset that has been created but not yet
 * consumed by a version bump operation. Each changeset is identified
 * by a unique ID derived from the branch name.
 *
 * # Fields
 *
 * - `id`: The unique changeset identifier
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface ChangesetInfo {
 *   Changeset ID (derived from branch name)
 *   id: string;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * const changeset: ChangesetInfo = { id: 'feature-add-login' };
 * const fix: ChangesetInfo = { id: 'fix-memory-leak' };
 * ```
 */
export interface ChangesetInfo {
  /**
   * Changeset unique identifier.
   *
   * This ID is typically derived from the Git branch name that
   * created the changeset. It uniquely identifies the changeset
   * within the workspace.
   */
  id: string
}

/**
 * Error information structure for Node.js bindings.
 *
 * This structure is exposed to JavaScript/TypeScript via napi-rs and provides
 * detailed error information in a format familiar to Node.js developers.
 * The `#[napi(object)]` attribute enables automatic conversion to JavaScript
 * objects and TypeScript type generation.
 *
 * # Fields
 *
 * - `code`: Node.js-style error code (e.g., "EVALIDATION", "EGIT")
 * - `message`: Human-readable error message
 * - `context`: Optional additional context (field name, path, etc.)
 * - `kind`: Error category from the CLI layer
 *
 * # TypeScript Definition
 *
 * ```typescript
 * export interface ErrorInfo {
 *   Node.js-style error code (e.g., "EVALIDATION", "EGIT")
 *   code: string;
 *   Human-readable error message
 *   message: string;
 *   Optional additional context about the error
 *   context?: string;
 *   Error category from CLI (for debugging)
 *   kind: string;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * // In JavaScript/TypeScript:
 * if (!result.success) {
 *   const { code, message, context, kind } = result.error;
 *   console.error(`[${code}] ${message}`);
 *   if (context) {
 *     console.error(`Context: ${context}`);
 *   }
 * }
 * ```
 */
export interface ErrorInfo {
  /**
   * Node.js-style error code (e.g., "EVALIDATION", "EGIT").
   *
   * These codes follow Node.js conventions and can be used for
   * programmatic error handling in JavaScript/TypeScript.
   *
   * # Available Codes
   *
   * - `ECONFIG`: Configuration errors
   * - `EVALIDATION`: Validation errors
   * - `EEXEC`: Execution errors
   * - `EGIT`: Git errors
   * - `EPKG`: Package errors
   * - `ENOENT`: File/path not found
   * - `EIO`: I/O errors
   * - `ENETWORK`: Network errors
   * - `EUSER`: User errors
   * - `ETIMEOUT`: Timeout errors
   */
  code: string
  /**
   * Human-readable error message.
   *
   * This message is suitable for displaying to end users and
   * provides a clear description of what went wrong.
   */
  message: string
  /**
   * Optional additional context for the error.
   *
   * This may contain the field name that caused a validation error,
   * the path that was not found, or other relevant context information.
   */
  context?: string
  /**
   * Error category from the CLI layer.
   *
   * This corresponds to the `CliError` variant name (e.g., "Configuration",
   * "Validation", "Git") and can be used for logging and debugging.
   */
  kind: string
}

/**
 * Returns the version of the crate.
 *
 * This function is exposed to Node.js and returns the current version
 * of the `sublime_node_tools` crate.
 *
 * # Returns
 *
 * A string containing the semantic version of the crate.
 *
 * # Examples
 *
 * ```typescript
 * import { getVersion } from '@websublime/workspace-tools';
 *
 * console.log(`Using workspace-tools version: ${getVersion()}`);
 * ```
 */
export declare function getVersion(): string

/**
 * Package information.
 *
 * Contains metadata about a single package within the workspace,
 * including its name, version, and relative path.
 *
 * # Fields
 *
 * - `name`: The package name (may include scope)
 * - `version`: The current package version
 * - `path`: The package path relative to workspace root
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface PackageInfo {
 *   Package name (may include scope like @org/package)
 *   name: string;
 *   Package version (semver)
 *   version: string;
 *   Package path relative to workspace root
 *   path: string;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * // Scoped package
 * const pkg: PackageInfo = {
 *   name: '@websublime/core',
 *   version: '1.2.3',
 *   path: 'packages/core'
 * };
 *
 * // Unscoped package
 * const utils: PackageInfo = {
 *   name: 'utils',
 *   version: '0.1.0',
 *   path: 'packages/utils'
 * };
 * ```
 */
export interface PackageInfo {
  /**
   * Package name.
   *
   * This is the name as defined in the package's `package.json`.
   * It may include a scope prefix (e.g., `@organization/package-name`).
   */
  name: string
  /**
   * Package version.
   *
   * The current version of the package as defined in its `package.json`.
   * Follows semantic versioning format (e.g., `1.2.3`, `0.1.0-beta.1`).
   */
  version: string
  /**
   * Package path relative to workspace root.
   *
   * This is the directory path where the package is located,
   * relative to the workspace root directory.
   * For simple repositories, this is typically `"."`.
   */
  path: string
}

/**
 * Package manager information.
 *
 * Contains details about the detected package manager being used
 * in the workspace, including the lock file name.
 *
 * # Fields
 *
 * - `name`: The package manager name
 * - `lock_file`: The name of the lock file used
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface PackageManagerInfo {
 *   Package manager name (npm, yarn, pnpm, bun, jsr, unknown)
 *   name: string;
 *   Lock file name
 *   lockFile: string;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * // pnpm package manager
 * const pnpm: PackageManagerInfo = {
 *   name: 'pnpm',
 *   lockFile: 'pnpm-lock.yaml'
 * };
 *
 * // npm package manager
 * const npm: PackageManagerInfo = {
 *   name: 'npm',
 *   lockFile: 'package-lock.json'
 * };
 * ```
 */
export interface PackageManagerInfo {
  /**
   * Package manager name.
   *
   * Possible values:
   * - `"npm"`: Node Package Manager
   * - `"yarn"`: Yarn package manager
   * - `"pnpm"`: pnpm package manager
   * - `"bun"`: Bun package manager
   * - `"jsr"`: JSR package manager
   * - `"unknown"`: Unable to detect package manager
   */
  name: string
  /**
   * Lock file name used by the package manager.
   *
   * Examples:
   * - `"package-lock.json"` for npm
   * - `"yarn.lock"` for Yarn
   * - `"pnpm-lock.yaml"` for pnpm
   * - `"bun.lockb"` for Bun
   */
  lockFile: string
}

/**
 * Repository type information.
 *
 * Contains information about the repository structure, indicating whether
 * it's a simple single-package repository or a monorepo with multiple packages.
 *
 * # Fields
 *
 * - `kind`: The repository type ("simple", "monorepo", or "unknown")
 * - `monorepo_type`: The monorepo type if applicable
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface RepositoryInfo {
 *   Repository kind: "simple", "monorepo", or "unknown"
 *   kind: string;
 *   Monorepo type if applicable (npm, yarn, pnpm, bun, deno, custom)
 *   monorepoType?: string;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * // Simple repository (single package)
 * const simple: RepositoryInfo = { kind: 'simple' };
 *
 * // Monorepo with pnpm workspaces
 * const monorepo: RepositoryInfo = {
 *   kind: 'monorepo',
 *   monorepoType: 'pnpm'
 * };
 * ```
 */
export interface RepositoryInfo {
  /**
   * Repository kind identifier.
   *
   * Possible values:
   * - `"simple"`: Single package repository
   * - `"monorepo"`: Multi-package workspace
   * - `"unknown"`: Unable to determine repository type
   */
  kind: string
  /**
   * Monorepo type if the repository is a monorepo.
   *
   * This field is only present when `kind` is `"monorepo"`.
   * Possible values include:
   * - `"npm"`: npm workspaces
   * - `"yarn"`: Yarn workspaces
   * - `"pnpm"`: pnpm workspaces
   * - `"bun"`: Bun workspaces
   * - `"deno"`: Deno workspaces
   * - `"custom"`: Custom workspace configuration
   */
  monorepoType?: string | undefined
}

/**
 * Get workspace status information.
 *
 * Returns comprehensive information about the workspace including repository type,
 * package manager, Git branch, pending changesets, and all workspace packages.
 *
 * This function is the main entry point for Node.js applications to retrieve
 * workspace status. It handles all the complexity of CLI invocation and response
 * parsing internally.
 *
 * @param params - Status parameters containing:
 *   - `root`: Workspace root directory path (required)
 *   - `configPath`: Optional custom config file path
 *
 * @returns `Promise<ApiResponse<StatusData>>` containing:
 *   - On success: `{ success: true, data: StatusData }`
 *   - On failure: `{ success: false, error: ErrorInfo }`
 *
 * @example Basic usage
 * ```typescript
 * const result = await status({ root: '/path/to/project' });
 * if (result.success) {
 *   console.log(`Found ${result.data.packages.length} packages`);
 *   console.log(`Package manager: ${result.data.packageManager.name}`);
 * } else {
 *   console.error(`Error: ${result.error.code} - ${result.error.message}`);
 * }
 * ```
 *
 * @example With custom config path
 * ```typescript
 * const result = await status({
 *   root: '/path/to/project',
 *   configPath: '/path/to/custom/repo.config.json'
 * });
 * ```
 *
 * @example Error handling
 * ```typescript
 * const result = await status({ root: '/nonexistent' });
 * if (!result.success) {
 *   if (result.error.code === 'ENOENT') {
 *     console.error('Path not found');
 *   } else if (result.error.code === 'EVALIDATION') {
 *     console.error('Invalid parameters');
 *   }
 * }
 * ```
 */
export declare function status(params: StatusParams): Promise<StatusApiResponse>

/**
 * API response for the status command.
 *
 * This is a concrete (non-generic) response type specifically for the status
 * command. It uses `#[napi(object)]` to enable automatic conversion to
 * JavaScript objects.
 *
 * napi-rs cannot use generic types with `#[napi(object)]`, so each command
 * that returns structured data needs its own concrete response type.
 *
 * # Fields
 *
 * - `success`: Whether the operation succeeded
 * - `data`: The status data (present when success is true)
 * - `error`: Error information (present when success is false)
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface StatusApiResponse {
 *   Whether the operation succeeded
 *   success: boolean;
 *   Status data (present on success)
 *   data?: StatusData;
 *   Error information (present on failure)
 *   error?: ErrorInfo;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * const result = await status({ root: '.' });
 *
 * if (result.success) {
 *   // result.data is StatusData
 *   console.log(result.data.repository.kind);
 * } else {
 *   // result.error is ErrorInfo
 *   console.error(`[${result.error.code}] ${result.error.message}`);
 * }
 * ```
 */
export interface StatusApiResponse {
  /**
   * Whether the operation succeeded.
   *
   * - `true`: Operation completed successfully, `data` field will be present
   * - `false`: Operation failed, `error` field will be present
   */
  success: boolean
  /**
   * The status data (only present when `success` is `true`).
   *
   * Contains comprehensive workspace information including repository type,
   * package manager, Git branch, pending changesets, and packages.
   */
  data?: StatusData | undefined
  /**
   * Error information (only present when `success` is `false`).
   *
   * Contains structured error information with a Node.js-style error code,
   * message, optional context, and error kind.
   */
  error?: ErrorInfo | undefined
}

/**
 * Status command response data.
 *
 * This is the main response structure returned by the status command,
 * containing comprehensive information about the workspace state.
 *
 * # Fields
 *
 * - `repository`: Repository type information
 * - `package_manager`: Package manager details
 * - `branch`: Current Git branch (if available)
 * - `changesets`: List of pending changesets
 * - `packages`: List of workspace packages
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface StatusData {
 *   Repository information
 *   repository: RepositoryInfo;
 *   Package manager information
 *   packageManager: PackageManagerInfo;
 *   Current branch (if available)
 *   branch?: BranchInfo;
 *   Pending changesets
 *   changesets: ChangesetInfo[];
 *   Workspace packages
 *   packages: PackageInfo[];
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * const status: StatusData = {
 *   repository: { kind: 'monorepo', monorepoType: 'pnpm' },
 *   packageManager: { name: 'pnpm', lockFile: 'pnpm-lock.yaml' },
 *   branch: { name: 'main' },
 *   changesets: [{ id: 'feature-login' }],
 *   packages: [
 *     { name: '@org/core', version: '1.0.0', path: 'packages/core' },
 *     { name: '@org/utils', version: '0.5.0', path: 'packages/utils' }
 *   ]
 * };
 * ```
 */
export interface StatusData {
  /**
   * Repository type information.
   *
   * Contains details about whether this is a simple repository
   * or a monorepo, and if monorepo, which type.
   */
  repository: RepositoryInfo
  /**
   * Package manager information.
   *
   * Details about the detected package manager and its lock file.
   */
  packageManager: PackageManagerInfo
  /**
   * Current Git branch information.
   *
   * This field is `None` if:
   * - Git is not available
   * - The directory is not a Git repository
   * - Git is in a detached HEAD state
   */
  branch?: BranchInfo | undefined
  /**
   * List of pending changesets.
   *
   * These are changesets that have been created but not yet
   * consumed by a version bump operation.
   */
  changesets: Array<ChangesetInfo>
  /**
   * List of workspace packages.
   *
   * For simple repositories, this contains a single package.
   * For monorepos, this contains all packages in the workspace.
   */
  packages: Array<PackageInfo>
}

/**
 * Input parameters for the status command.
 *
 * This structure defines the parameters that can be passed to the `status`
 * function from JavaScript/TypeScript. The root path is required, while
 * the config path is optional.
 *
 * # Fields
 *
 * - `root`: The workspace root directory path (required)
 * - `config_path`: Optional path to a custom configuration file
 *
 * # TypeScript Definition
 *
 * ```typescript
 * interface StatusParams {
 *   Workspace root directory path
 *   root: string;
 *   Optional custom config file path
 *   configPath?: string;
 * }
 * ```
 *
 * # Examples
 *
 * ```typescript
 * // Minimal params with just root
 * const params: StatusParams = { root: '.' };
 *
 * // With custom config path
 * const paramsWithConfig: StatusParams = {
 *   root: '/path/to/workspace',
 *   configPath: '/path/to/custom/repo.config.json'
 * };
 * ```
 */
export interface StatusParams {
  /**
   * Workspace root directory path.
   *
   * This is the absolute or relative path to the root of the workspace.
   * For monorepos, this should point to the root where the package manager
   * configuration (e.g., `pnpm-workspace.yaml`) is located.
   */
  root: string
  /**
   * Optional custom configuration file path.
   *
   * If not provided, the command will search for configuration files
   * in standard locations (`repo.config.json`, `repo.config.yaml`, etc.)
   * within the workspace root.
   */
  configPath?: string | undefined
}
