/**
 * @websublime/workspace-tools - Node.js bindings for workspace management
 *
 * This module provides the main entry point for the workspace-tools Node.js bindings.
 * It re-exports all functions and types from the native Rust bindings generated by napi-rs.
 *
 * ## What
 *
 * Re-exports all NAPI functions and TypeScript interfaces for:
 * - `getVersion()` - Get the version of the native bindings
 * - `status()` - Get workspace status information
 * - `init()` - Initialize workspace with changeset-based version management
 *
 * ## How
 *
 * The native bindings are compiled from Rust using napi-rs and exposed through
 * the `binding.js` and `binding.d.ts` files. This index module provides a clean
 * public API by selectively re-exporting the functions and types.
 *
 * ## Why
 *
 * Centralizing exports in an index file:
 * - Provides a stable public API surface
 * - Enables tree-shaking for bundlers
 * - Allows future refactoring without breaking changes
 * - Documents available exports in one place
 *
 * @packageDocumentation
 */

// Re-export all functions from bindings
import { getVersion, init, status } from './binding'

export { getVersion, init, status }

// Re-export all types from bindings
export type {
  // Error types
  ErrorInfo,

  // Init command types
  InitParams,
  InitApiResponse,
  InitData,

  // Status command types
  StatusParams,
  StatusApiResponse,
  StatusData,

  // Shared types
  RepositoryInfo,
  PackageManagerInfo,
  BranchInfo,
  ChangesetInfo,
  PackageInfo,
} from './binding'
