import {
  type AvailableUpgrade,
  type BumpOptions,
  ChangeType,
  Dependency,
  DependencyChange,
  DependencyFilter,
  DependencyGraph,
  DependencyRegistry,
  type DependencyUpdateInfo,
  DependencyUpgrader,
  type DotOptions,
  ExecutionMode,
  Node,
  Package,
  PackageDiff,
  PackageInfo,
  PackageRegistry,
  type RegistryAuthConfig,
  RegistryManager,
  RegistryType,
  ResolutionErrorType,
  type ResolutionResult,
  type UpgradeConfig,
  UpgradeStatus,
  type ValidationIssueInfo,
  ValidationIssueType,
  ValidationReport,
  Version,
  VersionComparisonResult,
  VersionStability,
  VersionUpdateStrategy,
  VersionUtils,
  buildDependencyGraphFromPackageInfos,
  buildDependencyGraphFromPackages,
  bumpSnapshotVersion,
  bumpVersion,
  createDefaultUpgradeConfig,
  createUpgradeConfigFromStrategy,
  createUpgradeConfigWithRegistries,
  generateAscii,
  generateDot,
  parseScopedPackage,
  saveDotToFile,
  getVersion,
} from './binding'

export type {
  AvailableUpgrade,
  BumpOptions,
  DependencyUpdateInfo,
  DotOptions,
  RegistryAuthConfig,
  ResolutionResult,
  UpgradeConfig,
  ValidationIssueInfo,
}

export {
  ChangeType,
  Dependency,
  DependencyChange,
  DependencyFilter,
  DependencyGraph,
  DependencyRegistry,
  DependencyUpgrader,
  ExecutionMode,
  Node,
  Package,
  PackageDiff,
  PackageInfo,
  PackageRegistry,
  RegistryManager,
  RegistryType,
  ResolutionErrorType,
  UpgradeStatus,
  ValidationIssueType,
  ValidationReport,
  Version,
  VersionComparisonResult,
  VersionStability,
  VersionUpdateStrategy,
  VersionUtils,
  buildDependencyGraphFromPackageInfos,
  buildDependencyGraphFromPackages,
  bumpSnapshotVersion,
  bumpVersion,
  createDefaultUpgradeConfig,
  createUpgradeConfigFromStrategy,
  createUpgradeConfigWithRegistries,
  generateAscii,
  generateDot,
  parseScopedPackage,
  saveDotToFile,
  getVersion,
}
